<?php
    
    namespace Inoma\FatturaElettronicaPR\Values;
    
    class TipoCassa {
        
        public const CASSA_NAZIONALE_PREVIDENZA_E_ASSISTENZA_AVVOCATI_E_PROCURATORI = "TC01";
        
        public const CASSA_PREVIDENZA_DOTTORI_COMMERCIALISTI = "TC02";
        
        public const CASSA_PREVIDENZA_E_ASSISTENZA_GEOMETRI = "TC03";
        
        public const CASSA_NAZIONALE_PREVIDENZA_E_ASSISTENZA_INGEGNERI_E_ARCHITETTI = "TC04";
        
        public const CASSA_NAZIONALE_DEL_NOTARIATO = "TC05";
        
        public const CASSA_NAZIONALE_PREVIDENZA_E_ASSISTENZA_RAGIONIERI_E_PERITI_COMMERCIALI = "TC06";
        
        public const ENTE_NAZIONALE_ASSISTENZA_AGENTI_E_RAPPRESENTANTI_DI_COMMERCIO = "TC07";
        
        public const ENTE_NAZIONALE_PREVIDENZA_E_ASSISTENZA_CONSULENTI_DEL_LAVORO = "TC08";
        
        public const ENTE_NAZIONALE_PREVIDENZA_E_ASSISTENZA_MEDICI = "TC09";
        
        public const ENTE_NAZIONALE_PREVIDENZA_E_ASSISTENZA_FARMACISTI = "TC10";
        
        public const ENTE_NAZIONALE_PREVIDENZA_E_ASSISTENZA_VETERINARI = "TC11";
        
        public const ENTE_NAZIONALE_PREVIDENZA_E_ASSISTENZA_IMPIEGATI_DELL_AGRICOLTURA = "TC12";
        
        public const FONDO_PREVIDENZA_IMPIEGATI_IMPRESE_DI_SPEDIZIONE_E_AGENZIE_MARITTIME = "TC13";
        
        public const ISTITUTO_NAZIONALE_PREVIDENZA_GIORNALISTI_ITALIANI = "TC14";
        
        public const OPERA_NAZIONALE_ASSISTENZA_ORFANI_SANITARI_ITALIANI = "TC15";
        
        public const CASSA_AUTONOMA_ASSISTENZA_INTEGRATIVA_GIORNALISTI_ITALIANI = "TC16";
        
        public const ENTE_PREVIDENZA_PERITI_INDUSTRIALI_E_PERITI_INDUSTRIALI_LAUREATI = "TC17";
        
        public const ENTE_PREVIDENZA_E_ASSISTENZA_PLURICATEGORIALE = "TC18";
        
        public const ENTE_NAZIONALE_PREVIDENZA_E_ASSISTENZA_BIOLOGI = "TC19";
        
        public const ENTE_NAZIONALE_PREVIDENZA_E_ASSISTENZA_PROFESSIONE_INFERMIERISTICA = "TC20";
        
        public const ENTE_NAZIONALE_PREVIDENZA_E_ASSISTENZA_PSICOLOGI = "TC21";
        
        public const INPS = "TC22";
    }
?>
